# Generated by Django 5.1.4 on 2025-01-14 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Product or service category')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company or person name')),
                ('company_id', models.CharField(blank=True, max_length=20, verbose_name='Company id')),
                ('vat_number', models.CharField(blank=True, max_length=50, verbose_name='VAT payer number')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Email adress')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone number')),
                ('address', models.CharField(max_length=255, verbose_name='Adress')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Invoice date')),
                ('due_date', models.DateField(verbose_name='Invoice payment date')),
                ('status', models.CharField(choices=[('PA', 'Paid'), ('PE', 'Pending'), ('OV', 'Overdue')], default='Pending', max_length=20, verbose_name='Invoice status')),
                ('apply_vat', models.BooleanField(default=False, verbose_name='Apply VAT')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='VAT amount in %')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apskaitininkas.client')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product or service name')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Product or service description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apskaitininkas.category')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Enter quantity of the products or services')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (leave blank to use product price)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='apskaitininkas.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apskaitininkas.productorservice')),
            ],
        ),
    ]
