# Generated by Django 5.1.4 on 2025-01-14 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apskaitininkas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='Invoice Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(verbose_name='Invoice issue date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(verbose_name='Invoice payment due date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PA', 'Paid'), ('PE', 'Pending'), ('OV', 'Overdue')], default='PE', max_length=20, verbose_name='Invoice status'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='VAT amount (%)'),
        ),
        migrations.CreateModel(
            name='ReceivedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True, verbose_name='Invoice number')),
                ('supplier', models.CharField(max_length=255, verbose_name='Supplier name')),
                ('issue_date', models.DateField(verbose_name='Invoice issue Date')),
                ('due_date', models.DateField(verbose_name='Invoice payment due date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total amount')),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VAT amount')),
                ('status', models.CharField(choices=[('PA', 'Paid'), ('PE', 'Pending'), ('OV', 'Overdue')], default='PE', max_length=20, verbose_name='Status')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='received_invoices/', verbose_name='PDF Invoice')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
        ),
    ]
