# Generated by Django 5.1.4 on 2025-01-14 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apskaitininkas', '0002_invoice_invoice_number_alter_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='receivedinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receivedinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PA', 'Paid'), ('PE', 'Pending'), ('OV', 'Overdue'), ('CA', 'Cancelled')], default='PE', max_length=20, verbose_name='Invoice status'),
        ),
        migrations.AlterField(
            model_name='receivedinvoice',
            name='status',
            field=models.CharField(choices=[('PA', 'Paid'), ('PE', 'Pending'), ('OV', 'Overdue'), ('CA', 'Cancelled')], default='PE', max_length=20, verbose_name='Status'),
        ),
    ]
