# Generated by Django 5.1.4 on 2025-01-14 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apskaitininkas', '0005_remove_transaction_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='related_company_id',
            new_name='company_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='related_party',
        ),
        migrations.AddField(
            model_name='transaction',
            name='issued_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apskaitininkas.issuedinvoice'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='received_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apskaitininkas.receivedinvoice'),
        ),
    ]
