# Generated by Django 5.1.4 on 2025-01-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apskaitininkas', '0006_rename_related_company_id_transaction_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Currency'),
        ),
    ]
