# Generated by Django 5.1.4 on 2025-01-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apskaitininkas', '0007_transaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedinvoice',
            name='name_of_goods',
            field=models.CharField(default=1, max_length=50, verbose_name='Name of goods'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receivedinvoice',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Enter quantity of the products or services'),
            preserve_default=False,
        ),
    ]
