# Generated by Django 5.1.4 on 2025-01-15 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apskaitininkas', '0008_receivedinvoice_name_of_goods_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedinvoice',
            name='name_of_goods',
        ),
        migrations.RemoveField(
            model_name='receivedinvoice',
            name='quantity',
        ),
    ]
