# Generated by Django 5.1.4 on 2025-01-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apskaitininkas', '0009_remove_receivedinvoice_name_of_goods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Cover image'),
        ),
    ]
