# Generated by Django 5.1.4 on 2025-01-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apskaitininkas', '0010_category_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedinvoice',
            name='apply_vat',
            field=models.BooleanField(default=False, verbose_name='Apply VAT'),
        ),
        migrations.AlterField(
            model_name='receivedinvoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount without VAT'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense')], max_length=10, verbose_name='Transaction type'),
        ),
    ]
